# Generated by Django 3.0.5 on 2020-05-16 14:52

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackupload',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='new', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='trackupload',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AlterField(
            model_name='trackupload',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
