# Generated by Django 3.0.5 on 2020-05-22 16:36

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_trackupload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackupload',
            name='conversion_type',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='preview', max_length=100, no_check_for_status=True),
        ),
    ]
